package com.example.minesweeper;

public enum Keys {
    BEGINNER_1_NAME,
    BEGINNER_1_TIME,
    BEGINNER_2_NAME,
    BEGINNER_2_TIME,
    BEGINNER_3_NAME,
    BEGINNER_3_TIME,
    INTERMEDIATE_1_NAME,
    INTERMEDIATE_1_TIME,
    INTERMEDIATE_2_NAME,
    INTERMEDIATE_2_TIME,
    INTERMEDIATE_3_NAME,
    INTERMEDIATE_3_TIME,
    EXPERT_1_NAME,
    EXPERT_1_TIME,
    EXPERT_2_NAME,
    EXPERT_2_TIME,
    EXPERT_3_NAME,
    EXPERT_3_TIME

}
